{% set name = "haystack-bm25" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/haystack_bm25-{{ version }}.tar.gz
  sha256: 57741c85203739d05e14de1a2c7657a675000a22dc7bd25f009eb9e0875ace2a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - haystack_bm25
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deepset-ai/rank_bm25
  summary: Various BM25 algorithms for document ranking
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-risch
